eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


microservice:
  logging-service:
    base-uri: http://LOGGING-SERVICE
    endpoints:
      system-logs-endpoint: /logs/test
        
  user-service:
    base-uri: http://USER-SERVICE
    endpoints:
      user-test-endpoint: /user/test


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    circuitbreakers:
      enabled: true
