eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: localhost



microservice:
  logging-service:
    base-uri: http://LOGGING-SERVICE
    endpoints:
      system-logs-endpoint: /logs/test
        
  user-service:
    base-uri: http://USER-SERVICE
    endpoints:
      user-test-endpoint: /user/test


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    circuitbreakers:
      enabled: true
