eureka:
  instance:
    # Use these settings for hostname/port registration
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: false
    
    # Add metadata for different access paths
    metadataMap:
      # For Prometheus in Docker
      docker.host: host.docker.internal
      docker.port: ${server.port}
      
      # For services on the same host
      local.host: localhost
      local.port: ${server.port}
      
    # Standard registration
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



microservice:
  logging-service:
    base-uri: http://LOGGING-SERVICE
    endpoints:
      system-logs-endpoint: /logs/test
        
  user-service:
    base-uri: http://USER-SERVICE
    endpoints:
      user-test-endpoint: /user/test


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    circuitbreakers:
      enabled: true
