eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



microservice:
  logging-service:
    endpoints:
      system-logs-endpoint:
        uri: http://LOGGING-SERVICE/logs/system
  user-service:
    endpoints:
      user-test-endpoint:
        uri: http://USER-SERVICE/user/test
